# Generated by Django 6.0.3 on 2026-03-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Courses',
            field=models.ManyToManyField(null=True, to='MyApp.course'),
        ),
    ]
