# Generated by Django 6.0.3 on 2026-03-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_teacher_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Courses',
            field=models.ManyToManyField(blank=True, to='MyApp.course'),
        ),
    ]
