# Generated by Django 6.0.2 on 2026-03-09 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Assessment1', models.CharField(max_length=50)),
                ('Assessment2', models.CharField(max_length=50)),
                ('Assessment3', models.CharField(max_length=50)),
                ('Assessment4', models.CharField(blank=True, max_length=50)),
                ('Assessment5', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.unit')),
            ],
        ),
    ]
