# Generated by Django 6.0.2 on 2026-03-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_unit_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='Assessment1',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Assessment2',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Assessment3',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Assessment4',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='Assessment5',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='id',
        ),
        migrations.AddField(
            model_name='unit',
            name='UnitID',
            field=models.CharField(default='test_unit', max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
