# Generated by Django 6.0.2 on 2026-03-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_remove_unit_assessment1_remove_unit_assessment2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='UnitID',
        ),
        migrations.AddField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
